// <auto-generated />
using Estimation.DataAccess;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage;
using Microsoft.EntityFrameworkCore.Storage.Internal;
using System;

namespace Estimation.DataAccess.Migrations
{
    [DbContext(typeof(MaterialDbContext))]
    partial class MaterialDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.0.1-rtm-125");

            modelBuilder.Entity("Estimation.DataAccess.Models.MainMaterialDb", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<int>("Code");

                    b.Property<string>("CodeAsString");

                    b.Property<DateTime?>("CreatedDate");

                    b.Property<DateTime?>("LastModifiedDate");

                    b.Property<string>("MaterialType");

                    b.Property<string>("Name")
                        .IsRequired();

                    b.HasKey("Id");

                    b.ToTable("MainMaterials");
                });

            modelBuilder.Entity("Estimation.DataAccess.Models.MaterialDb", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<int>("Code");

                    b.Property<string>("CodeAsString");

                    b.Property<DateTime?>("CreatedDate");

                    b.Property<decimal>("Fittings");

                    b.Property<DateTime?>("LastModifiedDate");

                    b.Property<decimal>("ListPrice");

                    b.Property<decimal>("Manpower");

                    b.Property<string>("MaterialType");

                    b.Property<string>("Name")
                        .IsRequired();

                    b.Property<decimal>("NetPrice");

                    b.Property<decimal>("OfferPrice");

                    b.Property<decimal>("Painting");

                    b.Property<string>("Remark");

                    b.Property<int>("SubMaterialId");

                    b.Property<decimal>("Supporting");

                    b.HasKey("Id");

                    b.HasIndex("SubMaterialId");

                    b.ToTable("Materials");
                });

            modelBuilder.Entity("Estimation.DataAccess.Models.SubMaterialDb", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<int>("Code");

                    b.Property<string>("CodeAsString");

                    b.Property<DateTime?>("CreatedDate");

                    b.Property<DateTime?>("LastModifiedDate");

                    b.Property<int>("MainMaterialId");

                    b.Property<string>("MaterialType");

                    b.Property<string>("Name");

                    b.HasKey("Id");

                    b.HasIndex("MainMaterialId");

                    b.ToTable("SubMaterials");
                });

            modelBuilder.Entity("Estimation.DataAccess.Models.MaterialDb", b =>
                {
                    b.HasOne("Estimation.DataAccess.Models.SubMaterialDb", "SubMaterial")
                        .WithMany("Materials")
                        .HasForeignKey("SubMaterialId")
                        .OnDelete(DeleteBehavior.Cascade);
                });

            modelBuilder.Entity("Estimation.DataAccess.Models.SubMaterialDb", b =>
                {
                    b.HasOne("Estimation.DataAccess.Models.MainMaterialDb", "MainMaterial")
                        .WithMany("SubMaterials")
                        .HasForeignKey("MainMaterialId")
                        .OnDelete(DeleteBehavior.Cascade);
                });
#pragma warning restore 612, 618
        }
    }
}
