// <auto-generated />
using Kaewsai.Utilities.Configurations;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage;
using System;

namespace Kaewsai.Utilities.Configurations.Migrations
{
    [DbContext(typeof(ConfigurationDbContext))]
    [Migration("20180317113328_InitialConfigurationDb")]
    partial class InitialConfigurationDb
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.0.2-rtm-10011");

            modelBuilder.Entity("Kaewsai.Utilities.Configurations.Models.Db.ConfigurationDictDb", b =>
                {
                    b.Property<string>("Title")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("Description");

                    b.HasKey("Title");

                    b.ToTable("ConfigurationDict");
                });

            modelBuilder.Entity("Kaewsai.Utilities.Configurations.Models.Db.ConfigurationEntriesDb", b =>
                {
                    b.Property<int>("ConfigurationEntryId")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("ConfigurationDictTitle")
                        .IsRequired();

                    b.Property<string>("EnglishDescription");

                    b.Property<string>("InternalDescription");

                    b.Property<string>("Label");

                    b.Property<string>("ThaiDescription");

                    b.Property<string>("Value");

                    b.HasKey("ConfigurationEntryId");

                    b.HasIndex("ConfigurationDictTitle");

                    b.ToTable("ConfigurationEntries");
                });

            modelBuilder.Entity("Kaewsai.Utilities.Configurations.Models.Db.ConfigurationEntriesDb", b =>
                {
                    b.HasOne("Kaewsai.Utilities.Configurations.Models.Db.ConfigurationDictDb", "ConfigurationDict")
                        .WithMany("ConfigurationEntries")
                        .HasForeignKey("ConfigurationDictTitle")
                        .OnDelete(DeleteBehavior.Cascade);
                });
#pragma warning restore 612, 618
        }
    }
}
